pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [joesan]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - base=master
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
      - status-success=build
    actions:
      merge:
        method: squash
